function stateKey = fn_readCoulbournStateKey()
stateKey = struct();

stateKey.stimulusKey = {{'Tone B Left','Tone B Left CT','Tone B Left ProbeIN','Tone 1 Left','Tone 1 Left CT','Tone 1 Left Probe'},...
    {'Tone A Right', 'Tone A Right CT', 'Tone 2 Right ProbeIN', 'Tone 2 Right', 'Tone 2 Right CT', 'Tone 2 Right Probe'} };

stateKey.contextKey = {{'Tone B Left','Tone A Right','Tone 1 Left','Tone 2 Right'},...
    {'Tone B Left CT','Tone A Right CT','Tone 1 Left CT','Tone 2 Right CT', },...
    { 'Tone B Left ProbeIN','Tone 2 Right ProbeIN','Tone 1 Left Probe', 'Tone 2 Right Probe'} };


stateKey.actionKey = {{'MISS Left','MISS Right','MISS Left CT','MISS Right CT','MISS Left Probe','MISS Right Probe',...
    'MISSdelay Probe Left','MISSdelay Probe Right'},...
    {'Reward Left', 'Non-Reward Left', 'FALSE Right', 'Reward Left CT', 'Non-Reward Left CT', 'FALSE Right CT',...
    'Reward Probe Left','Reward Left Probe','FALSEdelay Probe Right','FALSE Right Probe'},...
    {'Reward Right', 'Non-Reward Right','FALSE Left', 'Reward Right CT', 'Non-Reward Right CT','FALSE Left CT',...
    'Reward Probe Right', 'Reward Right Probe','FALSEdelay Probe Left', 'FALSE Left Probe'}};

stateKey.responseKey = {{'MISS Left','MISS Right','MISS Left CT','MISS Right CT','MISSdelay Probe Left','MISS Left Probe','MISSdelay Probe Right','MISS Right Probe'},...
    {'Reward Left', 'Non-Reward Left', 'Reward Right', 'Non-Reward Right', 'Reward Left CT', 'Non-Reward Left CT',...
    'Reward Right CT', 'Non-Reward Right CT','Reward Probe Left', 'Reward Left Probe','Reward Probe Right', 'Reward Right Probe'},...
    {'FALSE Left','FALSE Right','FALSE Left CT','FALSE Right CT','FALSEdelay Probe Left', 'FALSE Left Probe','FALSEdelay Probe Right','FALSE Right Probe'}};

stateKey.rewardKey = {
    {'Non-Reward Left','Non-Reward Right','Non-Reward Left CT','Non-Reward Right CT','Reward Probe Left', 'Reward Left Probe','Reward Probe Right', 'Reward Right Probe'...
    'FALSE Left','FALSE Right','FALSE Left CT','FALSE Right CT','FALSEdelay Probe Left', 'FALSE Left Probe','FALSEdelay Probe Right','FALSE Right Probe',...
    'MISS Left','MISS Right','MISS Left CT','MISS Right CT','MISSdelay Probe Left','MISS Left Probe','MISSdelay Probe Right','MISS Right Probe'},...
    {'Reward Left', 'Reward Right', 'Reward Left CT','Reward Right CT'}};

end